import { Row } from '@tanstack/react-table';

const today = new Date();
export const yesterday = new Date(today);
yesterday.setDate(today.getDate() - 1);

export const defaultReportValue = {
  searchCondition: {
    startDate: new Date(),
    endDate: new Date(),
    reportType: 0,
    isGroupTable: false,
  },
  selectedRows: [],
};

// export const dataTable = [];
export const dataTable = [
  {
    timeZone: '時間巿計',
    sales: 490,
    percentComplete: '',
    discountAmount: 0,
    score: 3,
    unitPrice: 148.7,
    numberOfGuests: 3,
    pricePerCustomer: 148.7,
    cumulativeSales: 312,
  },
  {
    timeZone: '01:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 0,
    pricePerCustomer: 0,
    cumulativeSales: 30,
  },
  {
    timeZone: '02:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 0,
    pricePerCustomer: 0,
    cumulativeSales: 0,
  },
  {
    timeZone: '03:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 0,
    pricePerCustomer: 0,
    cumulativeSales: 0,
  },
  {
    timeZone: '04:00',
    sales: 50,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 3,
    pricePerCustomer: 148.7,
    cumulativeSales: 46,
  },
  {
    timeZone: '05:00',
    sales: 20,
    percentComplete: '',
    discountAmount: 0,
    score: 3,
    unitPrice: 148.7,
    numberOfGuests: 3,
    pricePerCustomer: 148.7,
    cumulativeSales: 100,
  },
  {
    timeZone: '06:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 0,
    pricePerCustomer: 0,
    cumulativeSales: 0,
  },
  {
    timeZone: '07:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 0,
    pricePerCustomer: 0,
    cumulativeSales: 0,
  },
  {
    timeZone: '08:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 0,
    pricePerCustomer: 0,
    cumulativeSales: 0,
  },
  {
    timeZone: '09:00',
    sales: 30,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 3,
    pricePerCustomer: 148.7,
    cumulativeSales: 200,
  },
  {
    timeZone: '10:00',
    sales: 40,
    percentComplete: '',
    discountAmount: 0,
    score: 3,
    unitPrice: 148.7,
    numberOfGuests: 3,
    pricePerCustomer: 148.7,
    cumulativeSales: 0,
  },
  {
    timeZone: '11:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 0,
    pricePerCustomer: 0,
    cumulativeSales: 0,
  },
  {
    timeZone: '12:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 0,
    pricePerCustomer: 0,
    cumulativeSales: 0,
  },
  {
    timeZone: '13:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 0,
    pricePerCustomer: 0,
    cumulativeSales: 0,
  },
  {
    timeZone: '14:00',
    sales: 44,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 3,
    pricePerCustomer: 148.7,
    cumulativeSales: 10,
  },
  {
    timeZone: '15:00',
    sales: 446,
    percentComplete: '',
    discountAmount: 0,
    score: 3,
    unitPrice: 148.7,
    numberOfGuests: 3,
    pricePerCustomer: 148.7,
    cumulativeSales: 0,
  },
  {
    timeZone: '16:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 0,
    pricePerCustomer: 0,
    cumulativeSales: 0,
  },
  {
    timeZone: '17:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 0,
    pricePerCustomer: 0,
    cumulativeSales: 0,
  },
  {
    timeZone: '18:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 0,
    pricePerCustomer: 0,
    cumulativeSales: 0,
  },
  {
    timeZone: '19:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 3,
    pricePerCustomer: 148.7,
    cumulativeSales: 0,
  },
  {
    timeZone: '20:00',
    sales: 10,
    percentComplete: '',
    discountAmount: 0,
    score: 3,
    unitPrice: 148.7,
    numberOfGuests: 3,
    pricePerCustomer: 148.7,
    cumulativeSales: 0,
  },
  {
    timeZone: '21:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 0,
    pricePerCustomer: 0,
    cumulativeSales: 0,
  },
  {
    timeZone: '22:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 0,
    pricePerCustomer: 0,
    cumulativeSales: 0,
  },
  {
    timeZone: '23:00',
    sales: 0,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 0,
    pricePerCustomer: 0,
    cumulativeSales: 0,
  },
  {
    timeZone: '24:00',
    sales: 30,
    percentComplete: '',
    discountAmount: 0,
    score: 0,
    unitPrice: 0,
    numberOfGuests: 3,
    pricePerCustomer: 148.7,
    cumulativeSales: 0,
  },
];

export const dataTableDay = [
  {
    code: null,
    groupName: '*店合計*',
    sales: 100200,
    proportionOfRevenue: 500.83,
    numberOfGuests: 12,
    score: 12,
    discountAmount: 12,
    budget: 2400,
    timeZone: '08:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
  {
    code: '01',
    groupName: 'ＢＴ無頭えび',
    sales: 10,
    proportionOfRevenue: 22.4,
    numberOfGuests: 1,
    score: 1,
    discountAmount: 1,
    budget: 100,
    timeZone: '09:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
  {
    code: '02',
    groupName: 'ＢＴ無頭えび中',
    sales: 248,
    proportionOfRevenue: 55.6,
    numberOfGuests: 1,
    score: 1,
    discountAmount: 1,
    budget: 100,
    timeZone: '09:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
  {
    code: '03',
    groupName: '天然無頭えび',
    sales: 98,
    proportionOfRevenue: 22.0,
    numberOfGuests: 1,
    score: 1,
    discountAmount: 1,
    budget: 100,
    timeZone: '09:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
  {
    code: '04',
    groupName: 'ホワイト無頭えび中',
    sales: 248,
    proportionOfRevenue: 55.6,
    numberOfGuests: 1,
    score: 1,
    discountAmount: 1,
    budget: 100,
    timeZone: '09:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
  {
    code: '05',
    groupName: 'ホワイト無頭えび小',
    sales: 98,
    proportionOfRevenue: 22.0,
    numberOfGuests: 1,
    score: 1,
    discountAmount: 1,
    budget: 100,
    timeZone: '09:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
  {
    code: '06',
    groupName: '有頭えび',
    sales: 248,
    proportionOfRevenue: 55.6,
    numberOfGuests: 1,
    score: 1,
    discountAmount: 1,
    budget: 100,
    timeZone: '09:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
  {
    code: '07',
    groupName: 'むきえびその他',
    sales: 98,
    proportionOfRevenue: 22.0,
    numberOfGuests: 1,
    score: 1,
    discountAmount: 1,
    budget: 100,
    timeZone: '09:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
  {
    code: '08',
    groupName: 'シ－フドミックス',
    sales: 248,
    proportionOfRevenue: 55.6,
    numberOfGuests: 1,
    score: 1,
    discountAmount: 1,
    budget: 100,
    timeZone: '09:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
  {
    code: '09',
    groupName: 'えび関連品',
    sales: 98,
    proportionOfRevenue: 22.0,
    numberOfGuests: 1,
    score: 1,
    discountAmount: 1,
    budget: 100,
    timeZone: '09:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
  {
    code: '10',
    groupName: 'メニュー商品',
    sales: 248,
    proportionOfRevenue: 55.6,
    numberOfGuests: 1,
    score: 1,
    discountAmount: 1,
    budget: 100,
    timeZone: '09:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
  {
    code: '11',
    groupName: 'ちりめん・味付ちりめん',
    sales: 98,
    proportionOfRevenue: 22.0,
    numberOfGuests: 1,
    score: 1,
    discountAmount: 1,
    budget: 100,
    timeZone: '09:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
  {
    code: '12',
    groupName: '野菜',
    sales: 248,
    proportionOfRevenue: 55.6,
    numberOfGuests: 1,
    score: 1,
    discountAmount: 1,
    budget: 100,
    timeZone: '09:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
  {
    code: '13',
    groupName: '惣菜',
    sales: 98,
    proportionOfRevenue: 22.0,
    numberOfGuests: 1,
    score: 1,
    discountAmount: 1,
    budget: 100,
    timeZone: '09:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
  {
    code: '14',
    groupName: '野菜',
    sales: 248,
    proportionOfRevenue: 55.6,
    numberOfGuests: 1,
    score: 1,
    discountAmount: 1,
    budget: 100,
    timeZone: '09:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
  {
    code: '15',
    groupName: '惣菜',
    sales: 98,
    proportionOfRevenue: 22.0,
    numberOfGuests: 1,
    score: 1,
    discountAmount: 1,
    budget: 100,
    timeZone: '09:00',
    percentComplete: '',
    unitPrice: 150.4,
    pricePerCustomer: 160.8,
    cumulativeSales: 500,
  },
];
