spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://${DB_MASTER_URL:10.0.4.87:3306/m_ksm}?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Tokyo
      username: ${DB_USERNAME:posuser}
      password: ${DB_PASSWORD:poslove2023}
      minimum-idle: 5
      maximum-pool-size: 30
    transaction:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://${DB_TRANSACTION_URL:10.0.4.87:3306/t_ksm}?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Tokyo
      username: ${DB_USERNAME:posuser}
      password: ${DB_PASSWORD:poslove2023}
      minimum-idle: 5
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  profiles:
    active: local
  flyway:
    enabled: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

security:
  jwt:
    secret: XDZwPEXrav7ptKirUUKseGDZ6U6o5TKaSA2HqtCKzHy
    default-token: pJ2nr3RhLECBgXQA8hkeWgcznqQ6nBVIu9KNZ7wjBNZzi7LD81Ze1UTbz1dn59Ak11DtQ2bd5y5gtCFfYfjoQL
    refresh-token-expiration: 2592000000
    access-token-expiration: 2592000000
    app-token-key: XDZwPEXrav7ptKirUUKseGDZ6U6o5TKaSA2HqtCKzHy
    app-token-expiration: 2592000000
server:
  port: 8080

app:
  version: "@version@"

aws:
  s3:
    bucket-name: ${BUCKET_GIFT_NAME:aeon-gift-card}
    region: ${REGION_GIFT_NAME:ap-northeast-1}

log:
  upload:
    dir: ${LOG_UPLOAD_DIR:C:/Logs/Gift}

sftp:
  gift:
    host: ${SFTP_GIFT_HOST:210.144.93.18}
    port: ${SFTP_GIFT_PORT:22}
    username: ${SFTP_GIFT_USERNAME:80510048}
    remote-path: ${SFTP_GIFT_REMOTE_PATH:put/}
    private-key-path: ${SFTP_GIFT_KEY_PATH:C:\gift\sftp-key\key}
    key-passphrase: ${SFTP_GIFT_PASSPHRASE:''}

settlement:
  batch:
    folder-temp: ${SETTLEMENT_BATCH_FOLDER_TEMP:C:\gift\settlement}


