stages:
  - build
  - deploy

#Stage 1: Build FE
build:
  stage: build
  tags:
    - possystem
  rules:
    - if: $CI_COMMIT_REF_NAME == "ishida/staging"
  script:
    - npm install
    - npm run build-spk
    - TIMESTAMP=$(date +%Y%m%d%H%M%S)
    - RELEASE_DIR="/var/www/reactapp/releases/dist-$TIMESTAMP"
    - ssh -i /home/gitlab-runner/dev_key -o StrictHostKeyChecking=no $USER_DEV@$EC2_FE "mkdir -p $RELEASE_DIR"
    - rsync -az --delete -e "ssh -i /home/gitlab-runner/dev_key -o StrictHostKeyChecking=no" target/classes/static/* $USER_DEV@$EC2_FE:$RELEASE_DIR/
    - echo $RELEASE_DIR > release.txt
  artifacts:
    paths:
      - release.txt
    expire_in: 1 hour  

# Stage 3: Deploy to EC2
deploy:
  stage: deploy
  tags:
    - posapi
  rules:
    - if: $CI_COMMIT_REF_NAME == "ishida/staging"
  dependencies:
    - build
  script:
    - export RELEASE_DIR=$(cat release.txt)
    - echo $RELEASE_DIR
    - ssh -i /home/gitlab-runner/dev_key -o StrictHostKeyChecking=no $USER_DEV@$EC2_FE "ln -sfn $RELEASE_DIR /var/www/reactapp/current"

