package com.luvina.pos.provider.service;

import com.luvina.pos.provider.constant.CommonConstants;
import com.luvina.pos.provider.exception.S3OperationException;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import software.amazon.awssdk.core.ResponseInputStream;
import software.amazon.awssdk.core.sync.RequestBody;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.*;
import software.amazon.awssdk.services.s3.presigner.S3Presigner;
import software.amazon.awssdk.services.s3.presigner.model.GetObjectPresignRequest;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

@Service
@RequiredArgsConstructor
public class S3Service {
    private final S3Client s3Client;
    private final S3Presigner s3Presigner;
    @Value("${aws.s3.bucket-name}")
    private String bucketName;

    public List<String> listFiles(String folderPath) {
        String prefix = normalizePrefix(folderPath);

        try {
            ListObjectsV2Request req = ListObjectsV2Request.builder()
                    .bucket(bucketName)
                    .prefix(prefix)
                    .build();

            ListObjectsV2Response res = s3Client.listObjectsV2(req);

            if (res.contents().isEmpty()) {
                return Collections.emptyList();
            }

            return res.contents().stream()
                    .map(S3Object::key)
                    .filter(k -> !k.endsWith("/"))
                    .map(k -> k.substring(prefix.length()))  // remove folderPath
                    .toList();
        } catch (Exception e) {
            throw new S3OperationException(
                    CommonConstants.OperationType.LIST_FILES,
                    "Cannot list files from S3 folder: " + folderPath, e);
        }
    }

    public String generatePresignedUrl(String objectKey, long expireMinutes) {
        try {
            GetObjectRequest getObjectRequest = GetObjectRequest.builder()
                    .bucket(bucketName)
                    .key(objectKey)
                    .build();

            GetObjectPresignRequest presignRequest = GetObjectPresignRequest.builder()
                    .signatureDuration(java.time.Duration.ofMinutes(expireMinutes))
                    .getObjectRequest(getObjectRequest)
                    .build();

            return s3Presigner.presignGetObject(presignRequest).url().toString();

        } catch (Exception e) {
            throw new S3OperationException(
                    CommonConstants.OperationType.PRESIGN_URL,
                    "Failed to generate presigned URL for " + objectKey, e);
        }
    }

    /**
     * get InputStream in s3
     *
     * @param bucketName
     * @param key
     * @return
     */
    public InputStream getS3InputStream(String bucketName, String key) {
        GetObjectRequest getObjectRequest = GetObjectRequest.builder()
                .bucket(bucketName)
                .key(key)
                .build();

        ResponseInputStream<GetObjectResponse> s3InputStream = s3Client.getObject(getObjectRequest);
        return s3InputStream;
    }

    /**
     * Merge S3 Parts
     * Merge multiple S3 part files (generated by SELECT OUTFILE / UNLOAD)
     * into a single file using S3 Multipart Upload.
     *
     * @param bucket bucket name
     * @param sourcePrefix Prefix Folder containing exported part files
     * @param targetKey Final merged file key
     */
    public void mergeS3Parts(
            String bucket,
            String sourcePrefix,
            String targetKey
    ) throws IOException {

        // 1. List các file part
        List<S3Object> parts = new ArrayList<>();

        ListObjectsV2Request listReq = ListObjectsV2Request.builder()
                .bucket(bucket)
                .prefix(sourcePrefix)
                .build();

        ListObjectsV2Response listRes;
        do {
            listRes = s3Client.listObjectsV2(listReq);
            parts.addAll(listRes.contents());
            listReq = listReq.toBuilder()
                    .continuationToken(listRes.nextContinuationToken())
                    .build();
        } while (listRes.isTruncated());

        if (parts.isEmpty()) {
            throw new IllegalStateException("No part files found under " + sourcePrefix);
        }

        // 2. Sort đúng thứ tự part
        parts.sort(Comparator.comparing(S3Object::key));

        // 3. Create multipart upload cho file đích
        CreateMultipartUploadResponse createRes =
                s3Client.createMultipartUpload(
                        CreateMultipartUploadRequest.builder()
                                .bucket(bucket)
                                .key(targetKey)
                                .build()
                );

        String uploadId = createRes.uploadId();
        List<CompletedPart> completedParts = new ArrayList<>();

        int partNumber = 1;

        try {
            for (S3Object part : parts) {

                // 4. Stream từng part
                try (ResponseInputStream<GetObjectResponse> in =
                             s3Client.getObject(
                                     GetObjectRequest.builder()
                                             .bucket(bucket)
                                             .key(part.key())
                                             .build()
                             )) {

                    UploadPartResponse uploadPartRes =
                            s3Client.uploadPart(
                                    UploadPartRequest.builder()
                                            .bucket(bucket)
                                            .key(targetKey)
                                            .uploadId(uploadId)
                                            .partNumber(partNumber)
                                            .contentLength(part.size())
                                            .build(),
                                    RequestBody.fromInputStream(in, part.size())
                            );

                    completedParts.add(
                            CompletedPart.builder()
                                    .partNumber(partNumber)
                                    .eTag(uploadPartRes.eTag())
                                    .build()
                    );

                    partNumber++;
                }
            }

            // 5. Complete multipart upload
            s3Client.completeMultipartUpload(
                    CompleteMultipartUploadRequest.builder()
                            .bucket(bucket)
                            .key(targetKey)
                            .uploadId(uploadId)
                            .multipartUpload(
                                    CompletedMultipartUpload.builder()
                                            .parts(completedParts)
                                            .build()
                            )
                            .build()
            );

        } catch (Exception ex) {
            s3Client.abortMultipartUpload(
                    AbortMultipartUploadRequest.builder()
                            .bucket(bucket)
                            .key(targetKey)
                            .uploadId(uploadId)
                            .build()
            );

            throw ex;
        }
    }


    private String normalizePrefix(String folder) {
        if (folder == null || folder.isBlank()) return "";
        folder = folder.trim();
        return folder.endsWith("/") ? folder : folder + "/";
    }
}
